server/junkteam/quotes/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField, IntegerField, StringField, SelectField, validators, ValidationError, DecimalField
import phonenumbers
from flask_wtf import Form
from wtforms.fields.html5 import DateField

''' INTERNAL SUBDOMAIN BLUEPRINT '''
LOAD_SIZES_CHOICES = [('75.00', 'Min'),('120.00', '1/8'), ('160.00', '1/6'), 
                      ('210.00', '1/4'), ('315.00', '1/2'), ('400.00', '3/4'),
                      ('465.00', '1'), ('300','Dem'), ('50','Labour')]

class QuoteForm(FlaskForm):
    name = StringField('Name', [validators.DataRequired(), validators.Length(min=0, max=256)])
    email = StringField('Email', [validators.DataRequired(), validators.Email()])
    phone_number = StringField(
        'Phone#', [validators.DataRequired(), validators.Length(min=0, max=16)])
    address = StringField('Address', [
                          validators.DataRequired(), validators.Length(min=0, max=500)])
    est_volume = SelectField('Est load size:', choices=LOAD_SIZES_CHOICES)
    description = TextAreaField('Description/Notes', [validators.Length(min=0, max=1000)])
    dt = DateField('Pick a Day', [validators.DataRequired()], format='%Y-%m-%d')
    time = SelectField('Select a time:', choices=[('8:00', '8AM'), ('9:00', '9AM'), ('10:00', '10AM'),
                                                  ('11:00', '11AM'), ('12:00', 'Noon'), ('1:00', '1PM'),
                                                  ('2:00', '2PM'), ('3:00', '3PM'), ('4:00', '4PM'),
                                                  ('5:00', '5PM'), ('6:00', '6PM'), ('7:00', '7PM')])
    submit = SubmitField('Save Changes')

    def validate_phone_number(form, field):
        if len(field.data) > 16:
            raise ValidationError('Invalid phone number.')
        try:
            input_number = phonenumbers.parse(field.data)
            if not (phonenumbers.is_valid_number(input_number)):
                raise ValidationError('Invalid phone number.')
        except:
            input_number = phonenumbers.parse("+1"+field.data)
            if not (phonenumbers.is_valid_number(input_number)):
                raise ValidationError('Invalid phone number.')

class Add_Charge_Item_Form(FlaskForm):
    new_item = SelectField('Select Item:', choices=LOAD_SIZES_CHOICES)
    submit = SubmitField('Add Item to Charges')

 

server/junkteam/quotes/__init__.py
from flask import Blueprint

''' INTERNAL SUBDOMAIN BLUEPRINT '''

bp = Blueprint('quotes', __name__)
from junkteam.quotes import routes

server/junkteam/quotes/routes.py
from flask import render_template, url_for, request, redirect, session, flash, abort
from junkteam.models import Lead, Quote, Charge, Item, Items, Order
from junkteam.quotes import bp
from junkteam import app, db
# from werkzeug.urls import url_parse
from flask_login import login_required
from junkteam.quotes.forms import QuoteForm, LOAD_SIZES_CHOICES, Add_Charge_Item_Form


''' INTERNAL SUBDOMAIN BLUEPRINT '''

# Login page


#Quotes Dashboard - Loads in the current Quotes 
@bp.route('/', methods=['GET', 'POST'])
@login_required
def quotes():
    page = request.args.get('page', 1, type=int)
    quotes = Quote.query.order_by(Quote.quote_id.desc()).paginate(
        page, app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('quotes.quotes', page=quotes.next_num) \
        if quotes.has_next else None
    prev_url = url_for('quotes.quotes', page=quotes.prev_num) \
        if quotes.has_prev else None
    return render_template('quotes/quotes.html', title='Quotes',
                           quotes=quotes.items,
                           next_url=next_url, prev_url=prev_url)

#Quote Summary  - Loads in the selected Quote 
@bp.route('/quote/<quote_id>', methods=['GET', 'POST'])
@login_required
def quote(quote_id):

    quote = Quote.query.get(quote_id)
    if quote:
        charge = quote.charge
        items = Items.query.filter_by(charge_id=quote.charge.id).all()
        sub = quote.charge.get_subtotal() 
        tax = sub * 0.13
        total = sub * 1.13
        form = Add_Charge_Item_Form()
        if form.validate_on_submit():
            item_display = dict(LOAD_SIZES_CHOICES).get(form.new_item.data)
            item = Item.query.filter_by(lookup=item_display).first()
            items = Items.query.filter_by(charge_id=charge.id).all()
            item_to_add = Items(charge_id=charge.id, item_id = item.id, quantity = 1)
            print(f"Item to add: {item_to_add.item_id}  Items:{items}")

            for i in items:
                print(f"item ids? :  {i.item_id}")
                if item_to_add.item_id == i.item_id:
                    flash("Error")
                    return render_template('quotes/add_charge_item.html', form=form) 
            else:
                print("Trying to commit")
                db.session.add(item_to_add) 
                db.session.commit()
                update_cost(quote_id)
            return redirect(url_for('quotes.quote', quote_id=quote.quote_id))
        if quote.ordered:
            order = Order.query.filter_by(quote_id = quote_id).first()
            if not order:
                order = None
        else:
            order = None
        return render_template('quotes/quote.html', form=form, order=order, quote=quote, sub=sub, tax=tax, total=total, items=items)
    id = int(quote_id)
    if id != 0:
        quote = Quote.query.get(id-1)
        flash("Last Quote")
        return redirect(url_for('quotes.quote', quote_id=quote.quote_id))
    quote = Quote.query.get(id+1)
    return redirect(url_for('quotes.quote', quote_id=quote.quote_id))

# Create qute from Lead id
@bp.route('/create_quote/<id>', methods=['GET', 'POST'])
@login_required
def quote_from_lead(id):
    lead = Lead.query.get(id)
    form = QuoteForm()
    print(f"lead.est_volume: {lead.est_volume}")
    est_vol_dict = dict(LOAD_SIZES_CHOICES)
    for key, value in est_vol_dict.items():  
        if value == lead.est_volume:
            print(f"key: {key}")
            est_vol = key

    if form.validate_on_submit():
        est_load_display = dict(LOAD_SIZES_CHOICES).get(form.est_volume.data)
        print("Creating Quote")
        try:
            quote = Quote(name=form.name.data, email=form.email.data,
                        phone_number=form.phone_number.data,
                        address=form.address.data,
                        est_volume=est_load_display,
                        description=form.description.data, date=form.dt.data,
                        lead_id=id, userid=session["user_id"], time=form.time.data)
            db.session.add(quote)
            db.session.commit()
            print(f"New Quote ID: {quote.quote_id}")
            #create charge, add item, link to quote object and commit
            # MOVE TO A FUNCTION
            charge = Charge(quote_id=quote.quote_id)
            db.session.add(charge)
            db.session.commit()
            print(f"Lookup value: {est_load_display}")
            initial_item = Item.query.filter_by(lookup=est_load_display).first()
            if initial_item:
                print(f"Initial Item: {initial_item}")
            item_to_add = Items(charge_id=charge.id, item_id=initial_item.id, quantity = 1)
            db.session.add(item_to_add)
            db.session.commit()
            print(f"Quote ID for cost uodate: {quote.quote_id}")
            update_cost(quote.quote_id)
            
        except:
            print("Failed to create quote...")
        
        return redirect(url_for('quotes.quote', quote_id=quote.quote_id))
    return render_template('quotes/quote_from_lead.html', est_vol=est_vol, form=form, lead=lead)

# edit quotes
@bp.route('/edit_quote/<id>', methods=['GET', 'POST'])
@login_required
def edit_quote(id):
    quote = Quote.query.get(id)
    form = QuoteForm()
    print(f"Quote to edit: {quote}")
    if form.validate_on_submit():
        quote.name=form.name.data
        quote.email=form.email.data
        quote.phone_number=form.phone_number.data
        quote.address=form.address.data
        quote.description=form.description.data
        quote.date=form.dt.data
        quote.time=form.time.data
        db.session.commit()
        return redirect(url_for('quotes.quotes'))
    return render_template('quotes/edit_quote.html', form=form, quote=quote)




# Create Quote
@bp.route('/create_quote', methods=['GET', 'POST'])
@login_required
def create_quote():
    form = QuoteForm()
    
    if form.validate_on_submit():
        est_load_display = dict(LOAD_SIZES_CHOICES).get(form.est_volume.data)
        quote = Quote(name=form.name.data, email=form.email.data,
                      phone_number=form.phone_number.data,
                      address=form.address.data,
                      est_volume=est_load_display,
                      description=form.description.data, date=form.dt.data,
                      time=form.time.data)
        db.session.add(quote)
        db.session.commit()
        print(f"New Quote ID: {quote.quote_id}")
        #create charge, add item, link to quote object and commit
        # MOVE TO A FUNCTION
        charge = Charge(quote_id=quote.quote_id)
        db.session.add(charge)
        db.session.commit()
        print(f"Lookup value: {est_load_display}")
        initial_item = Item.query.filter_by(lookup=est_load_display).first()
        if initial_item:
            print(f"Initial Item: {initial_item}")
        item_to_add = Items(charge_id=charge.id, item_id=initial_item.id, quantity = 1)
        db.session.add(item_to_add)
        db.session.commit()
        print(f"Quote ID for cost uodate: {quote.quote_id}")
        update_cost(quote.quote_id)
     
        return redirect(url_for('quotes.quotes'))
    return render_template('quotes/create_quote.html', form=form)


def update_cost(id):
    quote = Quote.query.get(id)
    items = Items.query.filter_by(charge_id=quote.charge.id).all()
    sub = quote.charge.get_subtotal()
    quote.cost = sub
    db.session.commit()


# Delete Quote
@bp.route('/delete_quote/<id>')
@login_required
def delete_quote(id):
    quote = Quote.query.get_or_404(id)
    if quote.deleted:
        abort(404)
    quote.deleted = True
    db.session.commit()
    
    return redirect(url_for('quotes.quotes'))

@bp.route('/add_charge_item/<quote_id>', methods=['GET', 'POST'])
@login_required
def add_charge_item(quote_id):
    quote = Quote.query.get(quote_id)
    if quote.ordered:
        return redirect(url_for('quotes.quote', quote_id=quote.quote_id)) 
    charge = quote.charge
    form = Add_Charge_Item_Form()
    if form.validate_on_submit():
        item_display = dict(LOAD_SIZES_CHOICES).get(form.new_item.data)
        item = Item.query.filter_by(lookup=item_display).first()
        items = Items.query.filter_by(charge_id=charge.id).all()
        item_to_add = Items(charge_id=charge.id, item_id = item.id, quantity = form.quantity.data)
        print(f"Item to add: {item_to_add.item_id}  Items:{items}")

        for i in items:
            print(f"item ids? :  {i.item_id}")
            if item_to_add.item_id == i.item_id:
                flash("Error")
                return render_template('quotes/add_charge_item.html', form=form) 
        else:
            print("Trying to commit")
            db.session.add(item_to_add) 
            db.session.commit()
            update_cost(quote_id)
        return redirect(url_for('quotes.quote', quote_id=quote.quote_id))
    return render_template('quotes/add_charge_item.html', form=form)



@bp.route('/delete_charge_item')
@login_required
def delete_charge_item():
    quote_id = request.args.get('quote_id')
    item_id = int(request.args.get('item_id'))
    quote = Quote.query.get(quote_id)
    items = Items.query.filter_by(charge_id=quote.charge.id).all()
    print(f"Items: {items}")
    for item in items:
        if item.item.id == item_id:
            print(f"Item to Delete: {item.item}")
            del_items = db.session.query(Items).filter(Items.charge_id==quote.charge.id, Items.item_id==item_id).delete()
            print(f"Del: {del_items}")
            db.session.commit()
            update_cost(quote_id)
    print(f"Quote_id: {quote_id}")
    return redirect(url_for('quotes.quote', quote_id=quote.quote_id))

@bp.route('/decrement_charge_item')
@login_required
def decrement_charge_item():
    quote_id = request.args.get('quote_id')
    item_id = int(request.args.get('item_id'))
    quote = Quote.query.get(quote_id)
    items = Items.query.filter_by(charge_id=quote.charge.id).all()

server/junkteam/templates/quotes/add_charge_item.html
{% extends 'layouts/internal_layout.html' %}



{% block body %}

<form action='' method="post" id="add_charge_to_quote">

<p>
{{ form.new_item.label }}
{{ form.new_item() }}
{% for error in form.new_item.errors %}
        <span style="color: red;">[{{ error }}]</span>
{% endfor %}
</p>
<p>
        {{ form.quantity.label }}
        {{ form.quantity() }}
        {% for error in form.quantity.errors %}
                <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
        </p>
{{ form.csrf_token }}
<p>{{ form.submit() }}</p>


</form>
{% endblock %}

server/junkteam/templates/quotes/create_quote.html
{% extends 'layouts/internal_layout.html' %}



{% block body %}

<form action='' method="post" id="quoteform">



<p>
        {{ form.name.label }}
        {{ form.name(size=64  ) }}<br>
        {% for error in form.name.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
        {{ form.email.label }}
        {{ form.email(size=64) }}
        {% for error in form.email.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
        {{ form.phone_number.label }}
        {{ form.phone_number(size=64) }}<br>
        {% for error in form.phone_number.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
        {{ form.address.label }}
        {{ form.address(size=64) }}<br>
        {% for error in form.address.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
        {{ form.est_volume.label }}
        {{ form.est_volume() }}<br>
        {% for error in form.est_volume.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
{{ form.csrf_token }}
<p>

        {{ form.description.label }}
        {{ form.description(size=64) }}<br>
        {% for error in form.description.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
{{ form.dt.label }}
{{ form.dt(class='datepicker') }}
{% for error in form.dt.errors %}
        <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
</p>
<p>
{{ form.time.label }}
{{ form.time() }}
{% for error in form.time.errors %}
        <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
</p>

<p>{{ form.submit() }}</p>


</form>
{% endblock %}

server/junkteam/templates/quotes/edit_quote.html
{% extends 'layouts/internal_layout.html' %}



{% block body %}

<div>
    
<form class="form-horizontal" action='' method="post" id="edit_quoteform">


<h2>Edit Quote # {{quote.quote_id}}</h2><br>
<p>
        {{ form.name.label }}
        {{ form.name(size=64, value=quote.name) }}<br>
        {% for error in form.name.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
        {{ form.email.label }}
        {{ form.email(size=64, value=quote.email) }}
        {% for error in form.email.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
        {{ form.phone_number.label }}
        {{ form.phone_number(size=64, value=quote.phone_number) }}<br>
        {% for error in form.phone_number.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
        {{ form.address.label }}
        {{ form.address(size=64, value=quote.address) }}<br>
        {% for error in form.address.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

    <p style="visibility:hidden ">
            {{ form.est_volume.label }}
            {{ form.est_volume(id="est_vol") }}<br>
            {% for error in form.est_volume.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>

{{ form.csrf_token }}
<p>

        {{ form.description.label }}
        {{ form.description(size=64, id="description") }}<br>
        {% for error in form.description.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
{{ form.dt.label }}
{{ form.dt(class='datepicker', value=quote.date) }}
{% for error in form.dt.errors %}
        <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
</p>
<p>
{{ form.time.label }}
{{ form.time(id="time") }}
{% for error in form.time.errors %}
        <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
</p>

<p>{{ form.submit() }}</p>


</form>

<script> var textarea = document.getElementById('description'); textarea.innerHTML = "{{ quote.description }}" </script>
<script> var select = document.getElementById("time"); select.value = "{{ quote.time }}" </script>
{% endblock %}

server/junkteam/templates/quotes/quote.html
{% extends 'layouts/layout_no_sidebar.html' %}



{% block body %}
<style>
                table {
                  border-collapse: collapse;
                  border-spacing: 0;
                  width: 66%;
                  border: 1px solid #ddd;
                  margin-left: auto;
        margin-right: auto;
                }
                
                th, td {
                  text-align: left;
                  padding: 16px;
                }
                
                th {
                  color: whitesmoke;
                  background-color: #000000
                }
                .fas {
                        color: black;
                }

                </style>
<div>
        <h1 style="text-align: center; padding: 10px">
                
                <a href="/quotes/quote/{{ quote.quote_id - 1 }}"><i class="fas fa-arrow-left"></i></a>
                        Quote# {{quote.quote_id}} Summary
                <a href="/quotes/quote/{{ quote.quote_id + 1 }}"><i class="fas fa-arrow-right"></i></a>
        
        </h1>
</div>

<div class="container-fluid" style="width: 66%; padding:5px;">

  <div class="row">
                <div class="col"  >
                                Name: {{ quote.name }} <br>
                                Contact Email: {{ quote.email }} <br>
                                <hr>
                        </div>
        <div class="col " style="text-align: right ">

                        Address: {{ quote.address }} <br>
                        Date: {{ quote.date }} Time: {{ quote.time }} <br>
                        <hr>
                </div>
  </div>
</div>


<div>
<table border = "1">


        <tr>
                <th>Charges</th>
                <th>Price</th>
                <th style="text-align: center;">Quantity</th>
                <th style="text-align: center;">Delete</th>

                
                
        </tr>
        {% for item in items %}
        <tr>
                <td>{{item.item.name}}</td>
                <td>{{item.item.cost}}</td>
                <td style="text-align: center">
                   <div style="display: inline-flex">
                    <a href="/quotes/decrement_charge_item?quote_id={{quote.quote_id}}&item_id={{item.item.id}}"><i style = "padding: 4px" class="fas fa-minus-circle fa-2x "></i></a> 
                   <h4><span style = "position: 0px 4px" class="badge badge-secondary">{{item.quantity}}</span>    </h4>
                    <a href="/quotes/increment_charge_item?quote_id={{quote.quote_id}}&item_id={{item.item.id}}"><i style = "padding: 4px" class="fas fa-plus-circle fa-2x "></i></a>
                </div>
                </td>
                <td style="text-align: center;"><a href="/quotes/delete_charge_item?quote_id={{quote.quote_id}}&item_id={{item.item.id}}"><i class="fas fa-trash-alt fa-2x "></i></a> </td>
              
                
        </tr>
        {% endfor %}
        {% if not quote.ordered %}
        <tr>
                <td>
                        <form action='' method="post" id="add_charge_to_quote">        
                                {{ form.new_item.label }}
                                <span style="padding-right: 5px;">{{ form.new_item() }}</span>

                                {% for error in form.new_item.errors %}
                                        <span style="padding-right: 5px; color: red;">[{{ error }}]</span>
                                {% endfor %}

                                {{ form.csrf_token }}
                                {{ form.submit() }}
                        </form>
                </td>
        </tr>
        {% endif %}
</table>
<hr>
<table>

        {% if quote.discount %}
        
                <tr>
                        <td>Discount:</td>
                        <td>5000</td>
                </tr>
        
        {% endif %}
                              
                <tr>
                        <td>Sub Total:</td>
                        <td>{{sub}} </td>
                </tr>
                <tr>
                        <td>Tax (13%):</td>
                        <td>{{tax}} </td>
                </tr>
                <tr>
                        <td>Total:</td>
                        <td>{{total}} </td>
                </tr>
                


</table>
</div>
     
<div style="width: 66%; 
        padding:5px;
        margin-left: auto;
        margin-right: auto;">
        <div>

                {% if not quote.ordered %}
                <button>
                        <a href="/orders/create_order/{{ quote.quote_id }}">Confirm Order  <i class="fas fa-arrow-right"></i></a>  
                </button>

                {% else %}
                <a href="/orders/order/{{ order.order_id }}">Ordered<i class="fas fa-file-export"></i></a>
                {% endif %}
        
        
        </div>

        <div>

                        
                
        <!---
                <button>
                        <a href="/quotes/add_charge_item/{{ quote.quote_id }}">Add Charge  <i class="fas fa-arrow-right"></i></a>  
                </button>
        -->
        </div>

        <div>
                <button>
                        <a href="/quotes/quote/{{ quote.quote_id }}">Email Quote TODO  <i class="fas fa-arrow-right"></i></a>  
                </button>
        </div>

</div>





{% endblock %}

server/junkteam/templates/quotes/quote_from_lead.html
{% extends 'layouts/internal_layout.html' %}



{% block body %}

<div>
    
<form class="form-horizontal" action='' method="post" id="quoteform">



<p>
        {{ form.name.label }}
        {{ form.name(size=64, value=lead.name) }}<br>
        {% for error in form.name.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
        {{ form.email.label }}
        {{ form.email(size=64, value=lead.email) }}
        {% for error in form.email.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
        {{ form.phone_number.label }}
        {{ form.phone_number(size=64, value=lead.phone_number) }}<br>
        {% for error in form.phone_number.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
        {{ form.address.label }}
        {{ form.address(size=64, value=lead.address) }}<br>
        {% for error in form.address.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
        {{ form.est_volume.label }}
        {{ form.est_volume(id="est_vol") }}<br>
        {% for error in form.est_volume.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
{{ form.csrf_token }}
<p>

        {{ form.description.label }}
        {{ form.description(size=64, id="description") }}<br>
        {% for error in form.description.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
{{ form.dt.label }}
{{ form.dt(class='datepicker', value=lead.date) }}
{% for error in form.dt.errors %}
        <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
</p>
<p>
{{ form.time.label }}
{{ form.time(id="time") }}
{% for error in form.time.errors %}
        <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
</p>

<p>{{ form.submit() }}</p>


</form>

<script> var textarea = document.getElementById('description'); textarea.innerHTML = "{{ lead.description }}" </script>
<script> var select = document.getElementById("est_vol"); select.value = "{{ est_vol }}" </script>
<script> var select = document.getElementById("time"); select.value = "{{ lead.time }}" </script>
{% endblock %}

server/junkteam/templates/quotes/quotes.html
{% extends 'layouts/internal_layout.html' %}



{% block body %}
</div></div>



<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
<div>
<h2>Quotes</h2>
<a href="{{ url_for('quotes.create_quote', _anchor='quotes') }}">
    <span data-feather="plus-circle"></span>
    Add Quote
  </a>
    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th>ID#</th>
            <th>Timestamp</th>
            <th>Name</th>
            <th>Address</th>
            <th>Phone #</th>
            <th>Requested Date</th>
            <th>Time</th>
            <td>Description</td>
            <td>Est. Vol</td>
            <td>Cost</td>
            <td>Summary</td>
            <td>Edit</td>
               <td>Remove</td>
          </tr>
        </thead>
        <tbody>
          {% for quote in quotes %}
          {% if not quote.deleted %}
          <tr>
              
            <td><a href="/quotes/quote/{{ quote.quote_id }}">{{ quote.quote_id }}</a></td>
            <td>{{ quote.timestamp }}</td>
            <td>{{ quote.name }}</td>
            <td>{{ quote.address }}</td>
            <td>{{ quote.phone_number }}</td>
            <td>{{ quote.date }}</td>
            <td>{{ quote.time }}</td>
            <td>{{ quote.description }}</td>
            <td>{{ quote.est_volume }}</td>
            <td>{{ quote.cost }}</td>
            <td><a href="/quotes/quote/{{ quote.quote_id }}"><i class="fas fa-file-export"></i></a>  </td>
            <td><a href="/quotes/edit_quote/{{ quote.quote_id }}"><i class="fas fa-arrow-right"></i></a> </td>
            <td><a href="delete_quote/{{ quote.quote_id }}"><i class="fas fa-minus-circle"></i></a> </td>
          </tr>
          {% endif %}
          {% endfor %}
        </tbody>
      </table>
</div>

       {% if next_url %}
         <a  href="{{ next_url }}"><i class="fas fa-arrow-circle-left"></i>Older Quotes</a>
       {% endif %} |
       {% if prev_url %}
         <a  href="{{ prev_url }}">Newer Quotes<i class="fas fa-arrow-circle-right"></i></a>
       {% endif %}
</div>





</main>

  <!--- script -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
{% endblock %} 
</body>
</html>