server/junkteam/leads/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField, StringField, SelectField, validators, ValidationError
import phonenumbers
from flask_wtf import Form
from wtforms.fields.html5 import DateField
from junkteam import LOAD_SIZES_CHOICES
''' INTERNAL SUBDOMAIN BLUEPRINT '''

class LeadForm(FlaskForm):
    name = StringField('Name:', [validators.DataRequired(), validators.Length(min=0, max=256)])
    email = StringField('Email:', [validators.DataRequired(), validators.Email()])
    phone_number = StringField(
        'Phone #:', [validators.DataRequired(), validators.Length(min=0, max=16)])
    address = StringField('Address:', [
                          validators.DataRequired(), validators.Length(min=0, max=500)])
    est_volume = SelectField('Est load size:', choices=LOAD_SIZES_CHOICES)
    description = TextAreaField('Description/Notes:', [validators.Length(min=0, max=1000)])
    dt = DateField('Pick a Day', [validators.DataRequired()], format='%Y-%m-%d')
    time = SelectField('Select a time', choices=[('8:00', '8AM'), ('9:00', '9AM'), ('10:00', '10AM'),
                                                  ('11:00', '11AM'), ('12:00', 'Noon'), ('1:00', '1PM'),
                                                  ('2:00', '2PM'), ('3:00', '3PM'), ('4:00', '4PM'),
                                                  ('5:00', '5PM'), ('6:00', '6PM'), ('7:00', '7PM')])
    cost = StringField('Quoted Cost', [validators.Length(min=0, max=10)])
    submit = SubmitField()

    def validate_phone_number(form, field):
        if len(field.data) > 16:
            raise ValidationError('Invalid phone number.')
        try:
            input_number = phonenumbers.parse(field.data)
            if not (phonenumbers.is_valid_number(input_number)):
                raise ValidationError('Invalid phone number.')
        except:
            input_number = phonenumbers.parse("+1"+field.data)
            if not (phonenumbers.is_valid_number(input_number)):
                raise ValidationError('Invalid phone number.')

server/junkteam/leads/__init__.py
from flask import Blueprint

''' INTERNAL SUBDOMAIN BLUEPRINT '''

bp = Blueprint('leads', __name__)
from junkteam.leads import routes

server/junkteam/leads/routes.py
from flask import render_template, url_for, request, flash, redirect, session
from junkteam.leads import bp
from junkteam.models import Lead, Quote
from junkteam import app, db
from junkteam.leads.forms import LeadForm, LOAD_SIZES_CHOICES
# from werkzeug.urls import url_parse
from flask_login import login_required

''' INTERNAL SUBDOMAIN BLUEPRINT '''

#Leads Dashboard - Loads in the leads
@bp.route('/', methods=['GET', 'POST'] )
@login_required
def leads():
    page = request.args.get('page', 1, type=int)
    leads = Lead.query.order_by(Lead.lead_id.desc()).paginate(
        page, app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('leads.leads', page=leads.next_num) \
        if leads.has_next else None
    prev_url = url_for('leads.leads', page=leads.prev_num) \
        if leads.has_prev else None
    return render_template('leads/leads.html', title='Leads',
                           leads=leads.items,
                           next_url=next_url, prev_url=prev_url)

#Lead Summary  - Loads in the selected appointment 
@bp.route('/lead/<lead_id>', methods=['GET', 'POST'])
@login_required
def lead(lead_id):
    print(f"=====LEAD ID: {lead_id} ===========")
    lead = Lead.query.get(lead_id)
    if lead:                                     
        return render_template('leads/lead_summary.html', lead=lead)
    id = "89"
    id = int(lead_id)
    if id != 0:
        lead = Lead.query.get(id-1)
        flash("Last order")
        return redirect(url_for('leads.lead', lead_id=lead.lead_id))
    lead = Lead.query.get(id+1)
    return redirect(url_for('leads.lead', lead_id=lead.lead_id))

def availability(date, hour): 
    leads = Lead.query.filter_by(date=date).all()
    date_lead_times = {}
    if leads:
        for id, lead in enumerate(leads):
            date_lead_times[str(id)] = str(lead.time)

        for time in date_lead_times.values():
            print(time)
            if time == hour:
                print(f"Time Slot Taken at {hour}")
                return False
    return True


@bp.route('/create_lead', methods=['GET', 'POST'])
@login_required
def create_lead():
    form = LeadForm()
    if form.validate_on_submit():
        est_load_display = dict(LOAD_SIZES_CHOICES).get(form.est_volume.data)   
        time = form.time.data  
        date = form.dt.data 
        print(f"Testing time slot with time: {time} and date: {date} ")
        available = availability(date, time)
        if available:

            print("Timeslot available")
            lead = Lead(name=form.name.data, email=form.email.data, phone_number=form.phone_number.data,
                        address=form.address.data, est_volume=est_load_display, description=form.description.data, date=date, time=time)
            lead.cost = float(form.est_volume.data)
            db.session.add(lead)
            db.session.commit()
            print("TRYING TO FLASH")
            flash("Lead Created")
            return redirect(url_for('leads.leads'))
        flash("Time Taken")
        
    return render_template("leads/create_lead.html", form=form)




# edit lead
@bp.route('/edit_lead/<id>', methods=['GET', 'POST'])
@login_required
def edit_lead(id):
    lead = Lead.query.get(id)
    form = LeadForm()
    print(f"lead.est_volume: {lead.est_volume}")
    est_vol_dict = dict(LOAD_SIZES_CHOICES)
    for key, value in est_vol_dict.items():  
        if value == lead.est_volume:
            print(f"key: {key}")
            est_vol = key
    est_load_display = dict(LOAD_SIZES_CHOICES).get(form.est_volume.data)

    if form.validate_on_submit():
        lead.name=form.name.data
        lead.email=form.email.data
        lead.phone_number=form.phone_number.data
        lead.address=form.address.data
        lead.est_volume=est_load_display
        lead.description=form.description.data
        lead.date=form.dt.data
        lead.lead_id=id
        lead.userid=session["user_id"]
        lead.time=form.time.data
        lead.cost=form.est_volume.data
        db.session.commit()
        return redirect(url_for('leads.leads'))
    return render_template('leads/edit_lead.html', est_vol=est_vol, form=form, lead=lead)

# Delete Lead
@bp.route('/delete_lead/<id>')
@login_required
def delete_lead(id):
    Lead.query.filter_by(lead_id=id).delete()
    db.session.commit()
    return redirect(url_for('leads.leads'))

server/junkteam/templates/leads/create_lead.html
{% extends 'layouts/internal_layout.html' %}

{% block body %}

<div>
    
        <form class="form-horizontal" action='' method="post" id="leadform">
        
        <h2>Add Appoinment</h2>
        
        <p>
                {{ form.name.label }}
                {{ form.name(size=64) }}<br>
                {% for error in form.name.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
        
        <p>
                {{ form.email.label }}
                {{ form.email(size=64) }}
                {% for error in form.email.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
        
        <p>
                {{ form.phone_number.label }}
                {{ form.phone_number(size=64) }}<br>
                {% for error in form.phone_number.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
        
        <p>
                {{ form.address.label }}
                {{ form.address(size=64) }}<br>
                {% for error in form.address.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
        
        <p>
                {{ form.est_volume.label }}
                {{ form.est_volume(id="est_vol") }}<br>
                {% for error in form.est_volume.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
        {{ form.csrf_token }}
        <p>
        
                {{ form.description.label }}
                {{ form.description(size=64, id="description") }}<br>
                {% for error in form.description.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
        
        <p>
        {{ form.dt.label }}
        {{ form.dt(class='datepicker') }}
        {% for error in form.dt.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
        {{ form.time.label }}
        {{ form.time(id="time") }}
        {% for error in form.time.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        
        <p>{{ form.submit(label="Add") }}</p>
        
        
        </form>
        {% with messages = get_flashed_messages() %}
   {% if messages %}
      {% for message in messages %}
         {{ message }}
      {% endfor %}
   {% endif %}
{% endwith %}

{% endblock %}

server/junkteam/templates/leads/edit_lead.html
{% extends 'layouts/internal_layout.html' %}



{% block body %}

<div>
    
<form class="form-horizontal" action='' method="post" id="leadform">


<h2>Edit Appointment</h2>
<p>
        {{ form.name.label }}
        {{ form.name(size=64, value=lead.name) }}<br>
        {% for error in form.name.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
        {{ form.email.label }}
        {{ form.email(size=64, value=lead.email) }}
        {% for error in form.email.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
        {{ form.phone_number.label }}
        {{ form.phone_number(size=64, value=lead.phone_number) }}<br>
        {% for error in form.phone_number.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
        {{ form.address.label }}
        {{ form.address(size=64, value=lead.address) }}<br>
        {% for error in form.address.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
        {{ form.est_volume.label }}
        {{ form.est_volume(id="est_vol") }}<br>
        {% for error in form.est_volume.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
{{ form.csrf_token }}
<p>

        {{ form.description.label }}
        {{ form.description(size=64, id="description") }}<br>
        {% for error in form.description.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>

<p>
{{ form.dt.label }}
{{ form.dt(class='datepicker', value=lead.date) }}
{% for error in form.dt.errors %}
        <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
</p>
<p>
{{ form.time.label }}
{{ form.time(id="time") }}
{% for error in form.time.errors %}
        <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
</p>

<p>{{ form.submit() }}</p>


</form>
{% with messages = get_flashed_messages() %}
   {% if messages %}
      {% for message in messages %}
         {{ message }}
      {% endfor %}
   {% endif %}
{% endwith %}
<script> var textarea = document.getElementById('description'); textarea.innerHTML = "{{ lead.description }}" </script>
<script> var select = document.getElementById("est_vol"); select.value = "{{ est_vol }}" </script>
<script> var select = document.getElementById("time"); select.value = "{{ lead.time }}" </script>
{% endblock %}

server/junkteam/templates/leads/lead_summary.html
{% extends 'layouts/layout_no_sidebar.html' %}



{% block body %}
<style>
                table {
                  blead-collapse: collapse;
                  blead-spacing: 0;
                  width: 66%;
                  blead: 1px solid #ddd;
                  margin-left: auto;
        margin-right: auto;
                }
                
                th, td {
                  text-align: left;
                  padding: 16px;
                }
                
                th {
                  color: whitesmoke;
                  background-color: #000000
                }
                

                </style>

<div>
        <h1 style="text-align: center; padding: 10px">
        
                Appointment Summary# {{ lead.lead_id }}
                <a href="/quotes/create_quote/{{ lead.lead_id }}"><i class="fas fa-arrow-right"></i></a> 

        </h1>
</div>

<div class="container-fluid" style="width: 66%; padding:5px;">

    <div class="row">
        <div class="col"  >
            Name: {{ lead.name }} <br>
            Contact Email: {{ lead.email }} <br>
            Phone Number: {{ lead.phone_number }} <br>
            Address: {{ lead.address }} <a href="https://maps.google.com/?q={{lead.address}} Kingston Ontario"> <i class="fas fa-map-marker-alt"></i> </a><br>
            Date: {{ lead.date }} Time: {{ lead.time }} <br>
            <hr>
        </div>
        
        <div class="col " style="text-align: right ">
            Description: {{ lead.description }} <br>
            Est_Volume: {{ lead.est_volume }} <br>
            Est Cost: ${{ lead.cost }} <br>
              
            <hr>
        </div>
    </div>

</div>

  
  <a href="https://maps.google.com/?q={{lead.address}} Kingston Ontario"> </a>








{% endblock %}

server/junkteam/templates/leads/leads.html
{% extends 'layouts/internal_layout.html' %}



{% block body %}
</div></div>



  <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">

<div>
<h2>Appointments</h2> <a href="{{ url_for('leads.create_lead', _anchor='leads') }}">
    <span data-feather="plus-circle"></span>
    Add Appointment
  </a>
    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th>ID#</th>
            <th>Timestamp</th>
            <th>Name</th>
            <th>Address</th>
            <th>Phone #</th>
            <th>Requested Date</th>
            <th>Time</th>
            <td>Description</td>
            <td>Est. Vol</td>
            <td>Cost</td>
            <td>Edit</td>
            <th>Quote</th>
            <td>Delete</td>
          </tr>
            </thead>
          <tbody>
          {% for lead in leads %}
          <tr>
            <td><a href="/leads/lead/{{ lead.lead_id }}">{{ lead.lead_id }}</a></td>
            <td>{{ lead.timestamp }}</td>
            <td>{{ lead.name }}</td>
            <td>{{ lead.address }}</td>
            <td>{{ lead.phone_number }}</td>
            <td>{{ lead.date }}</td>
            <td>{{ lead.time }}</td>
            <td>{{ lead.description }}</td>
            <td>{{ lead.est_volume }}</td>
            <td>{{ lead.cost }}</td>
            <td><a href="/leads/edit_lead/{{ lead.lead_id }}"><i class="fas fa-arrow-right"></i></a> </td>
            <td><a href="/quotes/create_quote/{{ lead.lead_id }}"><i class="fas fa-arrow-right"></i></a>  </td>
            <td><a href="delete_lead/{{ lead.lead_id }}"><i class="fas fa-minus-circle"></i></a> </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>

       {% if next_url %}
         <a  href="{{ next_url }}"><i class="fas fa-arrow-circle-left"></i>Older Leads</a>
       {% endif %} |
       {% if prev_url %}
         <a  href="{{ prev_url }}">Newer Leads<i class="fas fa-arrow-circle-right"></i></a>
       {% endif %}
</div>
{% with messages = get_flashed_messages() %}
   {% if messages %}
      {% for message in messages %}
         {{ message }}
      {% endfor %}
   {% endif %}
{% endwith %}



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
{% endblock %}

</body>
</html>