server/junkteam/expenses/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, DecimalField, TextAreaField, StringField, SelectField, validators, ValidationError
from flask_wtf import Form


''' INTERNAL SUBDOMAIN BLUEPRINT '''

class ExpenseForm(FlaskForm):
    expense_type = SelectField('Expense Type:', choices=[(
        'Dump', 'Dump'), ('Fuel', 'Fuel'), ('Misc', 'Misc')])
    invoice_id = StringField('Invoice ID:', [validators.DataRequired()])
    cost = DecimalField('Cost:', [validators.DataRequired()])
    mileage = StringField('Mileage:')
    weight = StringField('Weight:')
    description = TextAreaField('Description/Notes:', [validators.Length(min=0, max=1000)])
    submit = SubmitField()

'''
    def validate_phone_number(form, field):
        if len(field.data) > 16:
            raise ValidationError('Invalid phone number.')
        try:
            input_number = phonenumbers.parse(field.data)
            if not (phonenumbers.is_valid_number(input_number)):
                raise ValidationError('Invalid phone number.')
        except:
            input_number = phonenumbers.parse("+1"+field.data)
            if not (phonenumbers.is_valid_number(input_number)):
                raise ValidationError('Invalid phone number.')
'''

server/junkteam/expenses/__init__.py
from flask import Blueprint


bp = Blueprint('expenses', __name__)
from junkteam.expenses import routes

server/junkteam/expenses/routes.py
from flask import render_template, url_for, request, redirect, session
from junkteam.expenses import bp
from junkteam import app, db
from junkteam.models import Expense
from junkteam.expenses.forms import ExpenseForm
# from werkzeug.urls import url_parse
from flask_login import login_required



#expenses Dashboard - Loads in the expenses
@bp.route('/', methods=['GET', 'POST'] )
@login_required
def expenses():
    page = request.args.get('page', 1, type=int)
    expenses = Expense.query.order_by(Expense.expense_id.desc()).paginate(
        page, app.config['POSTS_PER_PAGE'], False)
    next_url = url_for('expenses.expenses', page=expenses.next_num) \
        if expenses.has_next else None
    prev_url = url_for('expenses.expenses', page=expenses.prev_num) \
        if expenses.has_prev else None
    return render_template('expenses/expenses.html', title='Expenses',
                           expenses=expenses.items,
                           next_url=next_url, prev_url=prev_url)


@bp.route('/create_expense', methods=['GET', 'POST'])
@login_required
def create_expense():
    form = ExpenseForm()
    if form.validate_on_submit():
        expense = Expense(expense_type=form.expense_type.data, invoice_id=form.invoice_id.data, cost=form.cost.data,
                    mileage=form.mileage.data, weight=form.weight.data, description=form.description.data, userid=session["user_id"])
        db.session.add(expense)
        db.session.commit()
        return redirect(url_for('expenses.expenses'))
    return render_template("expenses/create_expense.html", form=form)



''' Don't edit or delete expenses - add admin priveledge
@bp.route('/edit_lead/<id>', methods=['GET', 'POST'])
@login_required
def edit_lead(id):
    lead = Lead.query.get(id)
    form = LeadForm()
    if form.validate_on_submit():
        lead.name=form.name.data
        lead.email=form.email.data
        lead.phone_number=form.phone_number.data
        lead.address=form.address.data
        lead.est_volume=form.est_volume.data
        lead.description=form.description.data
        lead.date=form.dt.data
        lead.lead_id=id
        lead.userid=session["user_id"]
        lead.time=form.time.data
        lead.cost=form.cost.data
        db.session.commit()
        return redirect(url_for('leads.leads'))
    return render_template('leads/update_lead.html', form=form, lead=lead)

# Delete Lead
@bp.route('/delete_lead/<id>')
@login_required
def delete_lead(id):
    Lead.query.filter_by(lead_id=id).delete()
    db.session.commit()
    return redirect(url_for('leads.leads'))

'''

server/junkteam/templates/expenses/create_expense.html
{% extends 'layouts/internal_layout.html' %}

{% block body %}

<div>
    
        <form class="form-horizontal" action='' method="post" id="expenseform">
        
        <h2>Add Expense</h2>
        
        <p>
                {{ form.expense_type.label }}
                {{ form.expense_type }}<br>
                {% for error in form.expense_type.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
        
        <p>
                {{ form.invoice_id.label }}
                {{ form.invoice_id(size=64) }}
                {% for error in form.invoice_id.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
        
        <p>
                {{ form.cost.label }}
                {{ form.cost(size=64) }}<br>
                {% for error in form.cost.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
        
        <p>
                {{ form.mileage.label }}
                {{ form.mileage(size=64) }}<br>
                {% for error in form.mileage.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
        
        <p>
                {{ form.weight.label }}
                {{ form.weight(size=64) }}<br>
                {% for error in form.weight.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
        {{ form.csrf_token }}
        <p>
        
                {{ form.description.label }}
                {{ form.description(size=64, id="description") }}<br>
                {% for error in form.description.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>

        
        <p>{{ form.submit(label="Add") }}</p>
        
        
        </form>
        

{% endblock %}

server/junkteam/templates/expenses/expenses.html
{% extends 'layouts/internal_layout.html' %}



{% block body %}
</div></div>




<main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">

<div>
<h2>Expenses</h2>

    <a href="{{ url_for('expenses.create_expense', _anchor='expenses') }}">
        <span data-feather="plus-circle"></span>
        Add Expense
    </a>
    
    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th>ID#</th>
            <th>Type</th>
            <th>Invoice ID</th>
            <th>Cost</th>
            <th>Time Stamp</th>
            <th>User</th>
            
          </tr>
        </thead>
        <tbody>
          {% for expense in expenses %}
          <tr>
            <td>{{ expense.expense_id }}</td>
            <td>{{ expense.expense_type }}</td>
            <td>{{ expense.invoice_id }}</td>
            <td>{{ expense.cost }}</td>
            <td>{{ expense.timestamp }}</td>
            <td>{{ expense.userid }}</td>
            
          </tr> 
          {% endfor %}
        </tbody>
      </table>
</div>

       {% if next_url %}
         <a  href="{{ next_url }}"><i class="fas fa-arrow-circle-left"></i>Older Expenses</a>
       {% endif %} |
       {% if prev_url %}
         <a  href="{{ prev_url }}">Newer Expenses<i class="fas fa-arrow-circle-right"></i></a>
       {% endif %}
</div>








<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

{% endblock %}
</body>


  </html>